GET http://localhost:5206

###

GET http://localhost:5206/projects

###

GET http://localhost:5206/projects/6842b2f8-1758-8013-bf37-894d525dcc42

####

POST http://localhost:5206/projects
Content-Type: Application/json

{
  "title": "Smart Home Energy System",
  "description": "Develop and install an IoT-based smart home energy management system to monitor electricity usage, integrate solar panels, and automate lighting and appliances.",
  "type": "Energy & Environment",
  "category": "Renewable Energy",
  "createdAt": "2025-10-25T09:00:00Z",
  "updatedAt": "2025-10-27T14:30:00Z",
  "startDate": "2025-10-28",
  "dueDate": "2025-12-15",
  "status": "active",
  "progress": 25,
  "priority": "high",
  "userId": "a9123c41-f5a2-4c23-a5d1-74b4b012bfc8",
  "allocats": [    
    "1e1e9b09-7b42-4a5b-9f9d-f8d7b5ef1b20",
    "4c76d9e0-442b-4a11-b7a9-1a92c7b1ed67",
    "cf3e2a5c-4c17-40a2-a7c3-8e3a0c31f9cb"
  ],
  "tasksCount": 12,
  "messagesCount": 24,
  "lastActivity": "2025-10-27T13:45:00Z",
  "isPublic": true,
  "allowBids": true,
  "budget": 6500,
  "currency": "USD",
  "attachments": [
    "https://picsum.photos/id/237/1000/760",
    "https://allocatr.s3.amazonaws.com/projects/ALC-1012/solar-layout.png"
  ]
}

###

PUT http://localhost:5206/projects/6842b2f8-1758-8013-bf37-894d525dcc41
Content-Type: application/json

{
  "id": "6842b2f8-1758-8013-bf37-894d525dcc41",
  "projectCode": "ALC-0001",
  "title": "Home Plumbing Repair",
  "description": "There are several leaks in my building. I need a major fix of leaks and replacement of faulty faucets in the residential property.",
  "type": "home service",
  "category": "plumbing",
  "createdAt": "2025-09-01T08:00:00Z",
  "updatedAt": "2025-09-10T08:00:00Z",
  "startDate": "2025-09-02",
  "dueDate": "2025-09-12",
  "status": "active",
  "progress": 60,
  "priority": "high",
  "userId": "1b02ab97-6b20-4b85-8c72-4f8c9e7f4a03",
  "allocats": [
    "c0a1a4d1-4b1f-45a3-8a7a-3a2f5a1c77c1",
    "ab23cd45-1234-4ef1-9b7a-99c2f8d5e888",
  ],
  "tasksCount": 4,
  "messagesCount": 12,
  "lastActivity": "2025-09-09T09:30:00Z",
  "isPublic": false,
  "allowBids": true,
  "budget": 250,
  "currency": "USD",
  "attachments": []
}

###

DELETE http://localhost:5206/projects/7d0c8331-3b24-4c7d-b6b7-5b517b92efc5
