GET http://localhost:5206

###

GET http://localhost:5206/projects

###

GET http://localhost:5206/projects/6842b2f8-1758-8013-bf37-894d525dcc42

####

POST http://localhost:5206/projects
Content-Type: Application/json

{
  "title": "Smart Home Energy System",
  "description": "Develop and install an IoT-based smart home energy management system to monitor electricity usage, integrate solar panels, and automate lighting and appliances.",
  "type": "Energy & Environment",
  "category": "Renewable Energy",
  "createdAt": "2025-10-25T09:00:00Z",
  "updatedAt": "2025-10-27T14:30:00Z",
  "startDate": "2025-10-28",
  "dueDate": "2025-12-15",
  "status": "active",
  "progress": 25,
  "priority": "high",
  "userId": "a9123c41-f5a2-4c23-a5d1-74b4b012bfc8",
  "allocats": [    
    
  ],
  "tasksCount": 12,
  "messagesCount": 24,
  "lastActivity": "2025-10-27T13:45:00Z",
  "isPublic": true,
  "allowBids": true,
  "budget": 6500,
  "currency": "USD",
  "attachments": [
    "https://picsum.photos/id/237/1000/760",
    "https://allocatr.s3.amazonaws.com/projects/ALC-1012/solar-layout.png"
  ]
}

###

PUT http://localhost:5206/projects/e341e6db-7101-4cb0-a4d8-ffc533201cd8
Content-Type: application/json

{
  "id": "e341e6db-7101-4cb0-a4d8-ffc533201cd8",
  "projectCode": "ALC-0001",
  "title": "Home Plumbing Repair",
  "description": "There are several leaks in my building. I need a major fix of leaks and replacement of faulty faucets in the residential property.",
  "type": "home service",
  "category": "plumbing",
  "createdAt": "2025-09-01T08:00:00Z",
  "updatedAt": "2025-09-10T08:00:00Z",
  "startDate": "2025-09-02",
  "dueDate": "2025-09-12",
  "status": "active",
  "progress": 60,
  "priority": "high",
  "userId": "1b02ab97-6b20-4b85-8c72-4f8c9e7f4a03",
  "allocats": [
    "c0a1a4d1-4b1f-45a3-8a7a-3a2f5a1c77c1",
    "ab23cd45-1234-4ef1-9b7a-99c2f8d5e888"
  ],
  "tasksCount": 4,
  "messagesCount": 12,
  "lastActivity": "2025-09-09T09:30:00Z",
  "isPublic": false,
  "allowBids": true,
  "budget": 250,
  "currency": "USD",
  "attachments": []
}

###

DELETE http://localhost:5206/projects/7d0c8331-3b24-4c7d-b6b7-5b517b92efc5

###

POST http://localhost:5206/api/auth/login
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "User1@email.com"
}

###

POST http://localhost:5206/api/allocats/profiles
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8M6Qw8wVAIVFgYjZKpvMVxhtVEFqNlmuTi0foh1EjjAVUGrmyV2lchtvaqXN13fFhOlmusK0-p3hBjHNMV0iwYC8oAiPgodiuBN046WYGO4wRuL18BYr4NIi2UL1TAZyvOAO_nPo3XXzj6_Vj6IhASUb5jxeovxfcokIl4i4kxkYH_y4yRgRoLhROXTIikHLz471bX7rM2d1VIzizCg0nf8sZe2nFaB_-0k-zxiFdVdtTsWQb749axToI-oy3yNePSWYGaeXa3nJCcs5xx3YLwjAaLG-RsTKCn0N7mYNYjJ8C_IRvJdqcJK_Hy-doNlEC-PB8HVOkukzkgUnzOVaWVLg4DqpmZwWgxImZBmWG0u3lDrzLRtykh1mfjuz1wJoC2tw3Q7BD5owczoGYsxwAOV0gJbhoADHSmqgSQ_C5Go-_tyZBRs2RIwo-_bShFTDHtUsfpgnkG4NAM3XLAdpf01FdSJfZeQuE5s2PirTzgWq1HttGH7Bf0e64Y35tale9-9o6uBpqrbZ7SekRcg-njn8mYSsJetW5_08mv9AYK5HRAtm4CYH1mA5NTPHYOCKSvtUWDqT65bYFpSWz_1FV5eotcn4zHnI0HfmD90lBqg6s6LeO9rOHMaN5NK5MD070r12JNvM8AX-7BqXNWbKy96bgLC1LeoTOaXDqENk-XkaHqiMgHvK6D7EnV_yzyXSw9Ui56VtJNRk9W4fLng6SkJKhRLln9B-68b-H1HipxN-_kvj9KXgw8gKlzTIyHsm5w

{
  "idNumber": "00000000C00",
  "hourlyRate": 21.00,
  "bio": "I the newest allocat on the block. I have 4 years of experience in home services and I'm ready to take on new projects and challenges.",
  "yearsExperience": 4
}

###

POST http://localhost:5206/api/skill-categories
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8NEyS35ZPeZPpfCGIzdS9ILlJpUyi6gV1Mr5PASpS1SrI9eOJqpOVe6xw9facV3bbkyrngmMCRCIUsznU9PwAHZFcXY4GnoBAlgILIRhRKKCOr-PdyAfldpcw4zphJCqAQY13W6zhs4y3ziM0KwQ6dhp8c8ou8bjpcDLmCj6nZY-Y5xF3blufxSB2rkjqZd2YRphfYhsDrEuFlv3WDuUo5UX3JSeRc3lfthpjY_3MOYVHE3MBUbT3LJhjuUH_XfqeU5VHNrSq-SPW3E1Qx6HzYml8ba0MdW39njeAueDfjdMAOZKOzR1JHCq0bNOV1n-b5cUmCQrZ4yo1rdssTICQg1hnc445puQZIpCeA-QO12c7U69qX2QDx_dyTQccQeH7X5kSRZU9RfnJLQHgZxAu0ftGQaxQwYLTjapFpf8gTe0YhbG3d3Zrto6EE18Vk4a6QxAngFZSdiDrMH14K-4cZBzLgwCJWQm0gl1xH2QjOwE-PDtSDB43PXYV2hXTCBOz_IZaMCEZ8CynX5DUSkfuXG2KhslypS6Dq_ax9rgn9u95czi9BRVVPGEG-GdRovHBNB2Fu9cb0YgLuljpGrb4kXPKYJspCUyChipqMH1hDF4RVbLLw0DxkX1HjknWxWXzpzietqMgOuOV1ryTSa5B1dNaQh4ZHhToJlqW36vZHNS2tuXUQyh7LjX1nSMzb6XlYy5yNSqirDskOQ7Tl_gx5HNnVQGlEkDzQf94klpWMoRUJDiDpOSfv-2MN8e5xGMyA

{
  "Name": "Home Service"
}

###

POST http://localhost:5206/api/skills
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8NEyS35ZPeZPpfCGIzdS9ILlJpUyi6gV1Mr5PASpS1SrI9eOJqpOVe6xw9facV3bbkyrngmMCRCIUsznU9PwAHZFcXY4GnoBAlgILIRhRKKCOr-PdyAfldpcw4zphJCqAQY13W6zhs4y3ziM0KwQ6dhp8c8ou8bjpcDLmCj6nZY-Y5xF3blufxSB2rkjqZd2YRphfYhsDrEuFlv3WDuUo5UX3JSeRc3lfthpjY_3MOYVHE3MBUbT3LJhjuUH_XfqeU5VHNrSq-SPW3E1Qx6HzYml8ba0MdW39njeAueDfjdMAOZKOzR1JHCq0bNOV1n-b5cUmCQrZ4yo1rdssTICQg1hnc445puQZIpCeA-QO12c7U69qX2QDx_dyTQccQeH7X5kSRZU9RfnJLQHgZxAu0ftGQaxQwYLTjapFpf8gTe0YhbG3d3Zrto6EE18Vk4a6QxAngFZSdiDrMH14K-4cZBzLgwCJWQm0gl1xH2QjOwE-PDtSDB43PXYV2hXTCBOz_IZaMCEZ8CynX5DUSkfuXG2KhslypS6Dq_ax9rgn9u95czi9BRVVPGEG-GdRovHBNB2Fu9cb0YgLuljpGrb4kXPKYJspCUyChipqMH1hDF4RVbLLw0DxkX1HjknWxWXzpzietqMgOuOV1ryTSa5B1dNaQh4ZHhToJlqW36vZHNS2tuXUQyh7LjX1nSMzb6XlYy5yNSqirDskOQ7Tl_gx5HNnVQGlEkDzQf94klpWMoRUJDiDpOSfv-2MN8e5xGMyA

{
  "Name": "Plumbing",
  "SkillCategoryId": "e518d182-0886-4728-a383-b7078efa859a"
}